# Generated by Django 5.0.1 on 2024-01-11 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('On The Way', 'On The Way'), ('Receive at delivery point', 'Receive at delivery point'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancel', 'Cancel')], max_length=50, null=True)),
                ('status_details', models.CharField(blank=True, max_length=600, null=True)),
                ('delivery_system', models.CharField(blank=True, choices=[('Train', 'Train'), ('Bus', 'Bus')], max_length=50, null=True)),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shipping_charge_paid', models.BooleanField(default=False)),
                ('shopping_payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=50, null=True)),
                ('pay_for', models.CharField(blank=True, choices=[('Pickup', 'Pickup'), ('Recipent', 'Recipent')], max_length=50, null=True)),
                ('delivery_secret_code', models.CharField(blank=True, max_length=6, null=True)),
                ('item_name', models.CharField(blank=True, max_length=500, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone_number', models.CharField(max_length=14)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_update', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='home.address')),
                ('pickup_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address', to='home.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
